
remote_theme: mmistakes/so-simple-theme

locale: tr-TR
title: "Blog|HG|"
description: "Hukuk|Yazılım|Felsefe|Tarih|Politika|Teknoloji"
baseurl: "/blog"
url: "https://hidayetgulec.github.io"
logo: "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: # 200
mathjax:
  enable: true
  combo: "tex-svg"
  tags: "ams"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "G-P5Y5W8C185"
disqus:
  shortname: "hidayetgulec"
twitter:
  username: "hidoyet"
google_site_verification: "A4SDYoxTOxXgt0TP8Oq4ZYdtW4FSQERogKKgFk8u6Xk"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: true

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Hidayet Güleç
  picture: /images/hidayetgulec.jpeg
  email: av.hidayetgulec@gmail.com
  twitter: hidoyet
  links:
    - title: Twitter
      url: https://twitter.com/hidoyet
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/hidoyet
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/hidayetgulec
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/hidoyet
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/hidayetgulec
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square